### ISSUE TITLE
Error with Craft3 release

### ISSUE THREAD

**Issue by bossanova808** [selvinortiz/craft-plugin-doxter#16]
Just updated to the released Craft3, and ran into this error with Doxter:

```
HP Notice 'yii\base\ErrorException' with message 'Undefined index: markup' 

in /var/www/vhosts/notes/vendor/erusev/parsedown-extra/ParsedownExtra.php:228

Stack trace:
#0 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 228)
#1 /var/www/vhosts/notes/vendor/erusev/parsedown-extra/ParsedownExtra.php(228): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/vhosts...', 228, Array)
#2 /var/www/vhosts/notes/vendor/erusev/parsedown/Parsedown.php(319): ParsedownExtra->blockMarkupComplete(Array)
#3 /var/www/vhosts/notes/vendor/erusev/parsedown/Parsedown.php(52): Parsedown->linesElements(Array)
#4 /var/www/vhosts/notes/vendor/erusev/parsedown/Parsedown.php(26): Parsedown->textElements('<ul>\n<li><code>...')
#5 /var/www/vhosts/notes/vendor/erusev/parsedown-extra/ParsedownExtra.php(46): Parsedown->text('<ul>\n<li><code>...')
#6 /var/www/vhosts/notes/vendor/selvinortiz/doxter/src/common/parsers/Markdown.php(43): ParsedownExtra->text('<ul>\n<li><code>...')
#7 /var/www/vhosts/notes/vendor/selvinortiz/doxter/src/services/DoxterService.php(116): selvinortiz\doxter\common\parsers\Markdown->parse('<ul>\n<li><code>...', Array)
#8 /var/www/vhosts/notes/vendor/selvinortiz/doxter/src/services/DoxterService.php(76): selvinortiz\doxter\services\DoxterService->parseMarkdown('<ul>\n<li><code>...')
#9 /var/www/vhosts/notes/vendor/selvinortiz/doxter/src/extensions/DoxterExtension.php(44): selvinortiz\doxter\services\DoxterService->parse('<ul>\n<li><code>...', Array)
#10 /var/www/vhosts/notes/storage/runtime/compiled_templates/c4/c4b6404095b26caf5e32445c15d7ac0c8504820dbf6a4c93fb3c3559e51a080a.php(58): selvinortiz\doxter\extensions\DoxterExtension->doxter(Object(selvinortiz\doxter\fields\data\DoxterData))
#11 /var/www/vhosts/notes/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_020436737de7e1e3dcac7fbf9a0b560cde8d87952af848e628c7c4e2f57415d1->doDisplay(Array, Array)
#12 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /var/www/vhosts/notes/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#15 /var/www/vhosts/notes/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#16 /var/www/vhosts/notes/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#17 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('/_ajax/notes', Array)
#18 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('/_ajax/notes', Array)
#19 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/Controller.php(113): craft\web\View->renderPageTemplate('/_ajax/notes', Array)
#20 /var/www/vhosts/notes/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('/_ajax/notes', Array)
#21 [internal function]: craft\controllers\TemplatesController->actionRender('/_ajax/notes', Array)
#22 /var/www/vhosts/notes/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/www/vhosts/notes/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('render', Array)
#25 /var/www/vhosts/notes/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#26 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/Application.php(238): yii\base\Module->runAction('templates/rende...', Array)
#27 /var/www/vhosts/notes/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#28 /var/www/vhosts/notes/vendor/craftcms/cms/src/web/Application.php(227): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/www/vhosts/notes/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /var/www/vhosts/notes/web/index.php(22): yii\base\Application->run()
#31 {main}
```

Not urgent - just a site I personally use for notes, but presume others will hit this soon!

**Comment by tjFogarty** [comment]
I'm having a similar issue:

```
yii\base\ErrorException: Undefined index: text in /Users/tjfogarty/Code/tj-craft/vendor/erusev/parsedown-extra/ParsedownExtra.php:193
Stack trace:
#0 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/tjfogart...', 193)
#1 /Users/tjfogarty/Code/tj-craft/vendor/erusev/parsedown-extra/ParsedownExtra.php(193): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/tjfogart...', 193, Array)
#2 /Users/tjfogarty/Code/tj-craft/vendor/erusev/parsedown/Parsedown.php(271): ParsedownExtra->blockHeader(Array, NULL)
#3 /Users/tjfogarty/Code/tj-craft/vendor/erusev/parsedown/Parsedown.php(52): Parsedown->linesElements(Array)
#4 /Users/tjfogarty/Code/tj-craft/vendor/erusev/parsedown/Parsedown.php(26): Parsedown->textElements('## About me\n\nI'...')
#5 /Users/tjfogarty/Code/tj-craft/vendor/erusev/parsedown-extra/ParsedownExtra.php(45): Parsedown->text('## About me\r\n\r\n...')
#6 /Users/tjfogarty/Code/tj-craft/vendor/selvinortiz/doxter/src/common/parsers/Markdown.php(43): ParsedownExtra->text('## About me\r\n\r\n...')
#7 /Users/tjfogarty/Code/tj-craft/vendor/selvinortiz/doxter/src/services/DoxterService.php(116): selvinortiz\doxter\common\parsers\Markdown->parse('## About me\r\n\r\n...', Array)
#8 /Users/tjfogarty/Code/tj-craft/vendor/selvinortiz/doxter/src/services/DoxterService.php(76): selvinortiz\doxter\services\DoxterService->parseMarkdown('## About me\r\n\r\n...')
#9 /Users/tjfogarty/Code/tj-craft/vendor/selvinortiz/doxter/src/fields/data/DoxterData.php(23): selvinortiz\doxter\services\DoxterService->parse('## About me\r\n\r\n...')
#10 /Users/tjfogarty/Code/tj-craft/vendor/selvinortiz/doxter/src/fields/DoxterField.php(92): selvinortiz\doxter\fields\data\DoxterData->__construct('## About me\r\n\r\n...')
#11 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/base/Element.php(1903): selvinortiz\doxter\fields\DoxterField->normalizeValue('## About me\r\n\r\n...', Object(craft\elements\Entry))
#12 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/base/Element.php(761): craft\base\Element->normalizeFieldValue('postContent')
#13 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/helpers/Template.php(57): craft\base\Element->__get('postContent')
#14 /Users/tjfogarty/Code/tj-craft/storage/runtime/compiled_templates/4f/4f8a313939a8bdcf37fb9d707700581947cddba0d1fa089979da8b5e99c41852.php(145): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Entry), 'postContent', Array)
#15 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_3842f885ed141e4b4a72f7348cf3e7ad4c7e8e4a537edcb036245b7d1bc80796->block_content(Array, Array)
#16 /Users/tjfogarty/Code/tj-craft/storage/runtime/compiled_templates/7b/7b81663194af1f46ad34d2e0a9074947692ecd645a18ca874c0d31240bc645ce.php(69): Twig_Template->displayBlock('content', Array, Array)
#17 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_933428dcd2a9741f2af224f511a1efdd7d769f3b7e74addd31dee525460275c5->doDisplay(Array, Array)
#18 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#19 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#21 /Users/tjfogarty/Code/tj-craft/storage/runtime/compiled_templates/4f/4f8a313939a8bdcf37fb9d707700581947cddba0d1fa089979da8b5e99c41852.php(28): craft\web\twig\Template->display(Array, Array)
#22 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_3842f885ed141e4b4a72f7348cf3e7ad4c7e8e4a537edcb036245b7d1bc80796->doDisplay(Array, Array)
#23 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#24 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#26 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#27 /Users/tjfogarty/Code/tj-craft/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#28 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/View.php(305): Twig_Environment->render('index', Array)
#29 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/View.php(352): craft\web\View->renderTemplate('index', Array)
#30 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/Controller.php(113): craft\web\View->renderPageTemplate('index', Array)
#31 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('index', Array)
#32 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#33 /Users/tjfogarty/Code/tj-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#34 /Users/tjfogarty/Code/tj-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#35 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('render', Array)
#36 /Users/tjfogarty/Code/tj-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#37 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/Application.php(244): yii\base\Module->runAction('templates/rende...', Array)
#38 /Users/tjfogarty/Code/tj-craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#39 /Users/tjfogarty/Code/tj-craft/vendor/craftcms/cms/src/web/Application.php(233): yii\web\Application->handleRequest(Object(craft\web\Request))
#40 /Users/tjfogarty/Code/tj-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#41 /Users/tjfogarty/Code/tj-craft/web/index.php(21): yii\base\Application->run()
#42 /Users/tjfogarty/.composer/vendor/laravel/valet/server.php(147): require('/Users/tjfogart...')
#43 {main}
```

On line 193 of `vendor/erusev/parsedown-extra/ParsedownExtra.php` I changed from:

``` php
if (preg_match('/[ #]*{(' . $this->regexAttribute . '+)}[ ]*$/', $Block['element']['text'], $matches, PREG_OFFSET_CAPTURE)) { ... }

```

to:

``` php
if (preg_match('/[ #]*{(' . $this->regexAttribute . '+)}[ ]*$/', $Block['element']['handler']['argument'], $matches, PREG_OFFSET_CAPTURE)) { ... }
```

and it seemed to resolve it, so I locked down `erusev/parsedown` to version 1.7.1 and it seems to work.

EDIT: Updated with a few more details, and I want to say thanks for a brilliant plugin. It's saved me so much time migrating content to Craft :)

**Comment by LukasKnuth** [comment]
I'm seeing the same error with the latest version. If I specifically require version `1.7.1`, the error is gone.

That being said, the [`1.8`-release](https://github.com/erusev/parsedown/releases/tag/1.8.0-beta-1) is marked as "Pre-Release", so for now the fix might be to just change the `composer.json` to explicitly require that version.

I'll check if I can find the issue and report it upstream.

**Comment by LukasKnuth** [comment]
I dug into this some more:

* The error was introduced [25 Days ago](https://github.com/erusev/parsedown/commit/098f24d189d17f6cadfdb135de6aa241576f3e35#diff-ed0d3da57330712681e64f838087ea47L516)
* It was fixed [9 Days ago](https://github.com/erusev/parsedown-extra/commit/bbf74b5f2a89b8c193f87fdc432806bc63cb0467#diff-6e93544faea52addc25721be4082dbb8L206)
* The fix is **not** part of the [current available release](https://github.com/erusev/parsedown-extra/releases/tag/0.7.1) which is now almost 3 years old!

I have [created an issue](https://github.com/erusev/parsedown-extra/issues/121) for it. For now, using the previous release of the parsedown-package (as suggested above) is the right way to go about this.

**Comment by bossanova808** [comment]
hmm, ok, I change this as per the pull request.  But the later version is proving stubborn....

I have tried `composer cleancache` and even nuking the entire vendor folder, but it still stubbornly insists on:

` - Installing erusev/parsedown (1.8.0-beta-1): Downloading (100%)`

The only other reference I can see is:
`vendor/enshrined/svg-sanitize/composer.lock:                "erusev/parsedown": "~1.0"`

...but that should not force it past the release version right?

Any further tips for relative newcomers to composer???

**Comment by selvinortiz** [comment]
Hi Everyone,
I apologize for my late response.
I appreciate you all for taking time to look into this issue.

I'm gonna cut a new release tomorrow (or the day after) to merge this pull request and another one that fixes an issue with the editor itself.

@bossanova808 I haven't had a chance to test and work through this issue myself, if I come across a solution for your case, I'll let you know.

**Comment by bossanova808** [comment]
Thanks Selvin.  This is basically an install running vanilla Craft3 and Doxter as the only plugin, so odd that the change in requirements is proving...stubborn!

Cheers, jeremy

**Comment by LukasKnuth** [comment]
## ACTUAL FIX BELOW!

@bossanova808 what version of Composer are you using?

To fix it temporarily, you can require the specific version directly: `composer require erusev/parsedown:1.7.1`. This will also add this specific version to your `composer.json`-document, so if you add this to git you will always get the desired version.

**Comment by LukasKnuth** [comment]
@bossanova808 I think I found it.

If you created your project when craft3 was still in beta, and you used the composer-template to create it, the templates `composer.json` has the following configuration:

      "minimum-stability": "beta",

This will cause composer to download beta packages, as opposed to the default setting which is `stable`. The (currently broken) "parsedown-extra"-package would not have been automatically updated if it weren't for that configuration. They have [changed it since](https://github.com/craftcms/craft/commit/8e8b970a5fe6b98f8cebebcf497f2bf0c3d8f857#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)

**So if you still have this setting in your `composer.json`, remove it!** Afterwards, no beta-packages will be used automatically, but you can still specifically require a beta-version.

---

For any problems with the (pretty complicated) composer syntax, you can check which package versions are included in a specific statement: https://semver.mwl.be

**Comment by selvinortiz** [comment]
@bossanova808 Nice!

**Comment by bossanova808** [comment]
@LukasKnuth @selvinortiz  Spot on - clearly I kept looking past that!   Thank you very much!

A quick removal of that line, nuke of the vendor folder, and composer update and all is working as it should again!
